/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config =
{
    address: '0.0.0.0',
    ipWhitelist: [
        '127.0.0.1',
        '::ffff:127.0.0.1',
        '::ffff:192.168.31.1/120',
        '192.168.31.1/24'
    ],
    modules: [
        {
            module: 'MMM-Snow',
            position: 'fullscreen_above',
            config: { // See 'Configuration options' for more information.
                flakeCount: 30,
                theme: "winter"
            }
        },
        {
            module: 'MMM-Remote-Control',
            config: {
                showModuleApiMenu: true,
                secureEndpoints: true
            }
        },
        {
            module: 'alert',
            config: {},
            header: '',
            position: ''
        },
        {
            module: 'updatenotification',
            position: 'top_bar',
            config: {}
        },
        {
            module: 'clock',
            position: 'top_left',
            clockBold: true,
            displayType: "both",
            config: {
                timeFormat: "24", // 24小时制
                dateFormat: "dddd, MMMM Do", // 修改为中文日期格式
                lang: "zh-cn" // 设置语言为中文
            },
            header: ''
        },
        {
            module: 'calendar',
            header: 'China_Holidays',
            position: 'top_left',
            config: {
                calendars: [
                    {
                        fetchInterval: 604800000,
                        symbol: 'calendar-check',
                        url: 'https://ics.calendarlabs.com/40/a973fd1a/China_Holidays.ics'
                    }
                ],
                showLocation: false,
                maximumEntries: 10,
                dateFormat: "YYYY-MM-DD dddd",
                fullDayEventDateFormat: "MM月DD日 dddd",
                displaySymbol: true,
                fade: true,
                urgency: 7
            }
        },
        {
            module: 'compliments',
            position: 'lower_third',
            config: {
                classes: 'thin',
                compliments: {
                    anytime: [
                        '你的微笑如春风般温暖，能够驱散所有的阴霾。',
                        '你拥有一种独特的魅力，总能让人感到舒适与愉悦。',
                        '你的气质优雅又自信，是最令人着迷的风景。',
                        '不论什么时候，你的美丽都像一首动人的诗，耐人寻味。',
                        '你的善良和智慧，让人从心底里生出敬佩之情。',
                        '你的眼神充满温柔与力量，像阳光一样让人倍感温暖。',
                        '你身上那种从容自信的气质，总能给人积极的能量。',
                        '你的笑容如阳光般灿烂，无论在哪里都能照亮一切。',
                        '不论何时，你都散发着迷人的光芒，无法忽视的存在。',
                        '你总是能够用自己的方式让这个世界变得更加美好。'
                    ],
                    morning: [
                        '你的微笑如清晨第一缕阳光，温暖而明亮。',
                        '清晨的你，如晨露般清新，如朝阳般耀眼。',
                        '你的气质像早晨的空气，纯净而迷人。',
                        '早晨的你，仿佛是一幅美丽的画卷，明媚动人。',
                        '晨曦中的你，如初绽的花朵，散发着迷人的芬芳。',
                        '你的眼眸像晨星一般璀璨，闪耀着希望与温柔。',
                        '清晨的风轻拂你的发丝，勾勒出你无比柔美的轮廓。',
                        '在这美好的清晨，你的笑容是天地间最动听的诗。',
                        '你的优雅，如清晨第一朵盛开的花，令人难以忘怀。',
                        '清晨的阳光映在你的脸庞，让你看起来如仙子般圣洁。'
                    ],
                    afternoon: [
                        '正午的阳光如同你的气质，温暖且耀眼，让人无法忽视。',
                        '在明亮的午间，你的笑容如同绽放的花朵，生机盎然。',
                        '你如正午的阳光般明媚，无时无刻不散发迷人的光彩。',
                        '在这阳光普照的中午，你的美丽更显得光芒四射。',
                        '你的优雅如午后微风，温柔地拂过人心。',
                        '正午的明亮与你的神采交相辉映，让世界都为之明亮。',
                        '中午时分，你的活力仿佛让周围的一切都焕发了生机。',
                        '在这阳光正浓的午间，你的美丽是一道令人心醉的风景。',
                        '中午的你，如阳光最耀眼的时刻般令人瞩目。',
                        '在这万物生长的正午时分，你的温暖和魅力是最美的风景。'
                    ],
                    evening: [
                        '夜晚的星光映在你的眼眸中，像璀璨的银河，美得让人心醉。',
                        '你的微笑比夜空中的月亮还要明亮，令人沉醉。',
                        '在这静谧的夜晚，你的优雅如夜风般轻柔，撩动人心。',
                        '你的美丽如夜空中的一颗明星，闪耀而迷人。',
                        '夜晚的灯火映衬出你温柔的身影，让人不舍得移开目光。',
                        '你的气质如夜晚的明月，高雅而迷人。',
                        '在这浪漫的夜晚，你的笑容是最温暖的光。',
                        '夜风吹过你的长发，仿佛为这夜晚增添了一份诗意。',
                        '你的温柔如夜晚的暖灯，给人安定和温馨的感觉。',
                        '夜色虽美，却远不及你的从容与优雅。'
                    ]
                }
            },
            header: ''
        },
        {
            module: 'weather',
            position: 'top_right',
            header: '天气预报',
            config: {
                weatherProvider: 'openmeteo',
                lat: 40.0372,
                lon: 116.310784,
                lang: 'zh'
            },
            header: ''
        },
        {
            module: 'weather',
            position: 'top_right',
            header: '天气预测',
            config: {
                weatherProvider: 'openmeteo',
                type: 'forecast',
                lat: 40.0372,
                lon: 116.310784,
                lang: 'zh'
            }
        },
        {
            module: 'newsfeed',
            position: 'bottom_bar',
            config: {
                feeds: [
                    {
                        title: '纽约时报',
                        url: 'https://cn.nytimes.com/rss.html'
                    }
                ]
            },
            header: ''
        },

        {
            module: 'mmm-systemtemperature',
            position: 'top_left',	// This can be any of the regions.
            classes: 'small dimmed', // Add your own styling. Optional.
            config: {
                prependString:'系统温度',
                updateInterval:10000,
                animationSpeed:1000,
            }
        },
        {
            module: 'MMM-Pir',
            position: 'top_left',
            config: {
              debug: true,
              Display: {
                timeout: 10 * 1000,
                animate: true,
                style: 1,
                colorFrom: "#FF0000",
                colorTo: "#00FF00",
                mode: 1,
                counter: true,
                lastPresence: true,
                lastPresenceTimeFormat: "LL H:mm",
                availability: true,
                autoDimmer: false,
                xrandrForceRotation: "normal",
                wrandrForceRotation: "normal",
                wrandrForceMode: null,
                waylandDisplayName: "wayland-0",
                relayGPIOPin: 0
              },
              Pir: {
                mode: 0,
                gpio: 21
              },
              Motion: {
                deviceId: 0,
                captureIntervalTime: 1000,
                scoreThreshold: 100
              },
              Cron: {
                ON: [],
                OFF: []
              },
              Touch: {
                mode: 3
              },
              Governor: {
                sleeping: 4,
                working: 2
              },
              Sounds: {
                on: "open.mp3",
                off: "close.mp3"
              }
            }
          },
    ],
    useHttps: false,
    httpsPrivateKey: '',
    httpsCertificate: '',
    units: 'metric',
    locale: 'zh',
    language: "zh-cn"
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') { module.exports = config; }
